export const IMAGES_FETCH_STARTED = 'IMAGES_FETCH_STARTED';
export const IMAGES_FETCH_COMPLETED = 'IMAGES_FETCH_COMPLETED';
export const IMAGES_FETCH_FAILED = 'IMAGES_FETCH_FAILED';

export const IMAGE_ADD_STARTED = 'IMAGE_ADD_STARTED';
export const IMAGE_ADD_COMPLETED = 'IMAGE_ADD_COMPLETED';
export const IMAGE_ADD_FAILED = 'IMAGE_ADD_FAILED';

export const IMAGE_REMOVE_STARTED = 'IMAGE_REMOVE_STARTED';
export const IMAGE_REMOVE_COMPLETED = 'IMAGE_REMOVE_COMPLETED';
export const IMAGE_REMOVE_FAILED = 'IMAGE_REMOVE_FAILED';


export const IMAGE_LIKE_STARTED = 'IMAGE_LIKE_STARTED';
export const IMAGE_LIKE_COMPLETED = 'IMAGE_LIKE_COMPLETED';
export const IMAGE_LIKE_FAILED = 'IMAGE_LIKE_FAILED';

export const IMAGE_EDIT_STARTED = 'IMAGE_EDIT_STARTED';
export const IMAGE_EDIT_COMPLETED = 'IMAGE_EDIT_COMPLETED';
export const IMAGE_EDIT_FAILED = 'IMAGE_EDIT_FAILED';