export const LINKS_FETCH_STARTED = 'LINKS_FETCH_STARTED';
export const LINKS_FETCH_COMPLETED = 'LINKS_FETCH_COMPLETED';
export const LINKS_FETCH_FAILED = 'LINKS_FETCH_FAILED';

export const LINK_ADD_STARTED = 'LINK_ADD_STARTED';
export const LINK_ADD_COMPLETED = 'LINK_ADD_COMPLETED';
export const LINK_ADD_FAILED = 'LINK_ADD_FAILED';

export const LINK_REMOVE_STARTED = 'LINK_REMOVE_STARTED';
export const LINK_REMOVE_COMPLETED = 'LINK_REMOVE_COMPLETED';
export const LINK_REMOVE_FAILED = 'LINK_REMOVE_FAILED';


export const LINK_LIKE_STARTED = 'LINK_LIKE_STARTED';
export const LINK_LIKE_COMPLETED = 'LINK_LIKE_COMPLETED';
export const LINK_LIKE_FAILED = 'LINK_LIKE_FAILED';

export const LINK_EDIT_STARTED = 'LINK_EDIT_STARTED';
export const LINK_EDIT_COMPLETED = 'LINK_EDIT_COMPLETED';
export const LINK_EDIT_FAILED = 'LINK_EDIT_FAILED';