export const NOTES_FETCH_STARTED = 'NOTES_FETCH_STARTED';
export const NOTES_FETCH_COMPLETED = 'NOTES_FETCH_COMPLETED';
export const NOTES_FETCH_FAILED = 'NOTES_FETCH_FAILED';

export const NOTE_ADD_STARTED = 'NOTE_ADD_STARTED';
export const NOTE_ADD_COMPLETED = 'NOTE_ADD_COMPLETED';
export const NOTE_ADD_FAILED = 'NOTE_ADD_FAILED';

export const NOTE_REMOVE_STARTED = 'NOTE_REMOVE_STARTED';
export const NOTE_REMOVE_COMPLETED = 'NOTE_REMOVE_COMPLETED';
export const NOTE_REMOVE_FAILED = 'NOTE_REMOVE_FAILED';

export const NOTE_LIKE_STARTED = 'NOTE_LIKE_STARTED';
export const NOTE_LIKE_COMPLETED = 'NOTE_LIKE_COMPLETED';
export const NOTE_LIKE_FAILED = 'NOTE_LIKE_FAILED';
