export const POSTER_FETCH_STARTED = 'POSTER_FETCH_STARTED';
export const POSTER_FETCH_COMPLETED = 'POSTER_FETCH_COMPLETED';
export const POSTER_FETCH_FAILED = 'POSTER_FETCH_FAILED';

// export const POSTER_IMAGE_FETCH_STARTED = 'POSTER_IMAGE_FETCH_STARTED';
// export const POSTER_IMAGE_FETCH_COMPLETED = 'POSTER_IMAGE_FETCH_COMPLETED';
// export const POSTER_IMAGE_FETCH_FAILED = 'POSTER_IMAGE_FETCH_FAILED';

export const POSTER_MESSAGES_FETCH_STARTED = 'POSTER_MESSAGES_FETCH_STARTED';
export const POSTER_MESSAGES_FETCH_COMPLETED = 'POSTER_MESSAGES_FETCH_COMPLETED';
export const POSTER_MESSAGES_FETCH_FAILED = 'POSTER_MESSAGES_FETCH_FAILED';

