export const VIDEOS_FETCH_STARTED = 'VIDEOS_FETCH_STARTED';
export const VIDEOS_FETCH_COMPLETED = 'VIDEOS_FETCH_COMPLETED';
export const VIDEOS_FETCH_FAILED = 'VIDEOS_FETCH_FAILED';

export const VIDEO_ADD_STARTED = 'VIDEO_ADD_STARTED';
export const VIDEO_ADD_COMPLETED = 'VIDEO_ADD_COMPLETED';
export const VIDEO_ADD_FAILED = 'VIDEO_ADD_FAILED';

export const VIDEO_REMOVE_STARTED = 'VIDEO_REMOVE_STARTED';
export const VIDEO_REMOVE_COMPLETED = 'VIDEO_REMOVE_COMPLETED';
export const VIDEO_REMOVE_FAILED = 'VIDEO_REMOVE_FAILED';


export const VIDEO_LIKE_STARTED = 'VIDEO_LIKE_STARTED';
export const VIDEO_LIKE_COMPLETED = 'VIDEO_LIKE_COMPLETED';
export const VIDEO_LIKE_FAILED = 'VIDEO_LIKE_FAILED';

export const VIDEO_EDIT_STARTED = 'VIDEO_EDIT_STARTED';
export const VIDEO_EDIT_COMPLETED = 'VIDEO_EDIT_COMPLETED';
export const VIDEO_EDIT_FAILED = 'VIDEO_EDIT_FAILED';